# encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Bookmark.create!(name: "google", url: "http://www.google.com.tw/ig?hl=zh-TW&source=iglk", domain_name: "www.google.com.tw")
Bookmark.create!(name: "Gmail", url: "http://mail.google.com/mail/?hl=zh-TW&tab=wm#", domain_name: "mail.google.com")
Bookmark.create!(name: "RSS", url: "http://www.google.com.tw/reader/view/?hl=zh-TW&tab=wy#overview-page", domain_name: "www.google.com.tw")
Bookmark.create!(name: "PPTV", url: "http://cool.pptv.com/", domain_name: "cool.pptv.com")
Bookmark.create!(name: "Raphael", url: "http://www.facebook.com/profile.php?ref=profile&id=100000246047412", domain_name: "www.facebook.com")
Bookmark.create!(name: "TED", url: "http://www.ted.com/translate/languages/chi_hant", domain_name: "www.ted.com")
Bookmark.create!(name: "Wiki", url: "http://www.wikipedia.org/", domain_name: "www.wikipedia.org")
Bookmark.create!(name: "YouTube", url: "http://www.youtube.com/", domain_name: "www.youtube.com")
Bookmark.create!(name: "Converter", url: "http://www.youtube-mp3.org/", domain_name: "www.youtube-mp3.org")
Bookmark.create!(name: "記錄", url: "chrome://chrome/history/", domain_name: "chrome")
Bookmark.create!(name: "Volife 開發日誌", url: "http://rf0914.blogspot.tw/", domain_name: "rf0914.blogspot.tw")
Bookmark.create!(name: "Stack Overflow", url: "http://stackoverflow.com/", domain_name: "stackoverflow.com")
Bookmark.create!(name: "TANGO", url: "http://candle.fl.nthu.edu.tw/totalrecall/totalrecall/totalrecall.aspx?funcID=1", domain_name: "candle.fl.nthu.edu.tw")
Bookmark.create!(name: "Corpus of Contemporary American English (COCA)", url: "http://corpus.byu.edu/coca/", domain_name: "corpus.byu.edu")
Bookmark.create!(name: "CARE", url: "http://candle.fl.nthu.edu.tw/care/WebForm1.aspx", domain_name: "candle.fl.nthu.edu.tw")
Bookmark.create!(name: "Longman English Dictionary Online", url: "http://www.ldoceonline.com/", domain_name: "www.ldoceonline.com")
Bookmark.create!(name: "Oxford Dictionaries Online", url: "http://oxforddictionaries.com/", domain_name: "oxforddictionaries.com")
Bookmark.create!(name: "TestMagic Test Prep", url: "http://www.testmagic.com/test/ViewDtlEssay.asp?StudentID=6756&TopicID=84", domain_name: "www.testmagic.com")
Bookmark.create!(name: "政治與英語 - 维基百科，自由的百科全书", url: "http://zh.wikipedia.org/wiki/%E6%94%BF%E6%B2%BB%E8%88%87%E8%8B%B1%E8%AA%9E", domain_name: "zh.wikipedia.org")
Bookmark.create!(name: "Speech Accent Archive", url: "http://accent.gmu.edu/", domain_name: "accent.gmu.edu")
Bookmark.create!(name: "facebook research - Google 學術搜尋", url: "http://scholar.google.com/scholar?q=facebook+research&hl=zh-TW&as_sdt=0&as_vis=1&oi=scholart&sa=X&ei=N3EOULWtN8vmmAW9pIAQ&ved=0CFgQgQMwAA", domain_name: "scholar.google.com")
Bookmark.create!(name: "HowStuffWorks \"Learn how Everything Works!\"", url: "http://www.howstuffworks.com/", domain_name: "www.howstuffworks.com")
Bookmark.create!(name: "thesaurus - Google 搜尋", url: "https://www.google.com/search?aq=f&sugexp=chrome,mod=4&sourceid=chrome&client=ubuntu&channel=cs&ie=UTF-8&q=thesaurus", domain_name: "www.google.com")
Bookmark.create!(name: "SoapME", url: "http://dl.acm.org/citation.cfm?id=1462802.1462805&coll=DL&dl=ACM&CFID=98498949&CFTOKEN=58878844", domain_name: "dl.acm.org")
Bookmark.create!(name: "oxford shoes - Google 搜尋", url: "https://www.google.com.tw/search?source=ig&hl=zh-TW&rlz=1G1GGLQ_ZH-TWTW336&q=oxford+shoes&oq=oxford+shoes&gs_l=igoogle.3..0l10.1562442.1566521.0.1566712.12.9.0.3.3.0.94.422.9.9.0...0.0...1ac.YlHU5E03XPA", domain_name: "www.google.com.tw")
Bookmark.create!(name: "Study in USA - GRE, F1 Visa, H1B Visa 2013", url: "http://www.happyschoolsblog.com/", domain_name: "www.happyschoolsblog.com")
Bookmark.create!(name: "Design Tips for a Cleaner User Interface | Tips", url: "http://webdesignledger.com/tips/design-tips-for-a-cleaner-user-interface", domain_name: "webdesignledger.com")
Bookmark.create!(name: "桶裝飲品:元氣先生 會議點心,活動餐盒,咖啡,潛艇堡,貝果,外送,下午茶,早午餐,蛋糕,團購", url: "http://www.mrogenki.com/website_module_detail.php?website_module_classify_sn=85&website_module_sn=1", domain_name: "www.mrogenki.com")
Bookmark.create!(name: "IAC 2012", url: "http://iac2012livingbetter.blogspot.tw/", domain_name: "iac2012livingbetter.blogspot.tw")
Bookmark.create!(name: "season of love - Google 搜尋", url: "https://www.google.com/search?q=season+of+love&aq=0&oq=senson+of+lo&sugexp=chrome,mod=4&sourceid=chrome&ie=UTF-8", domain_name: "www.google.com")
Bookmark.create!(name: "Omniauth Facebook Error - Faraday::Error::ConnectionFailed - Stack Overflow", url: "http://stackoverflow.com/questions/10775640/omniauth-facebook-error-faradayerrorconnectionfailed", domain_name: "stackoverflow.com")
Bookmark.create!(name: "Computer Network 2012", url: "http://www.cmlab.csie.ntu.edu.tw/~lawlietdo/CN2012/", domain_name: "www.cmlab.csie.ntu.edu.tw")
Bookmark.create!(name: "國立臺灣大學", url: "http://www.ntu.edu.tw/", domain_name: "www.ntu.edu.tw")
Bookmark.create!(name: "台大電機系 | NTUEE", url: "http://www.ee.ntu.edu.tw/", domain_name: "www.ee.ntu.edu.tw")
Bookmark.create!(name: "台大電機系學會", url: "https://sites.google.com/site/ntueeinfo/", domain_name: "sites.google.com")
Bookmark.create!(name: "電機系十選二實驗說明", url: "http://ntuee.org/eelab/", domain_name: "ntuee.org")
Bookmark.create!(name: "國立臺灣大學暑期課程網", url: "http://coursemap.aca.ntu.edu.tw/summer/", domain_name: "coursemap.aca.ntu.edu.tw")
Bookmark.create!(name: "課程網", url: "https://nol.ntu.edu.tw/nol/guest/index.php", domain_name: "nol.ntu.edu.tw")
Bookmark.create!(name: "選課輔助程式", url: "http://ntucourse.ericyu.org/schedule.php", domain_name: "ntucourse.ericyu.org")
Bookmark.create!(name: "NTU WebMail :: 使用者選項", url: "https://wmail1.cc.ntu.edu.tw/index.php?url=https%3A%2F%2Fwmail1.cc.ntu.edu.tw%2F", domain_name: "wmail1.cc.ntu.edu.tw")
Bookmark.create!(name: "國立臺灣大學 學生事務處 學生住宿服務組", url: "http://dorm.osa.ntu.edu.tw/main.php", domain_name: "dorm.osa.ntu.edu.tw")
Bookmark.create!(name: "台大課程地圖", url: "http://coursemap.aca.ntu.edu.tw/course_map_all/class.php?code=9020", domain_name: "coursemap.aca.ntu.edu.tw")
Bookmark.create!(name: "NTCIR HOME", url: "http://research.nii.ac.jp/ntcir/index-en.html", domain_name: "research.nii.ac.jp")
Bookmark.create!(name: "Motivation Article: Motivate Yourself for Success: Connect the Dots! Your Roadmap to Success", url: "http://www.thesykesgrp.com/MotivateConnectDots01.htm", domain_name: "www.thesykesgrp.com")
Bookmark.create!(name: "w3school - Google 搜尋", url: "https://www.google.com.tw/search?aq=0&oq=w3s&sourceid=chrome&client=ubuntu&channel=cs&ie=UTF-8&q=w3school", domain_name: "www.google.com.tw")
Bookmark.create!(name: "www.cfsm.cn/info/symbols/symbols.htm", url: "http://www.cfsm.cn/info/symbols/symbols.htm", domain_name: "www.cfsm.cn")
Bookmark.create!(name: "BinaryAge Store", url: "https://sites.fastspring.com/binaryage/order/complete;jsessionid=9D514148BAB2B9A02DAF49B20F82269C?csid=3598285", domain_name: "sites.fastspring.com")
Bookmark.create!(name: "www.tekritisoftware.com/sites/default/files/Socket_Programing_for_IOS.pdf", url: "http://www.tekritisoftware.com/sites/default/files/Socket_Programing_for_IOS.pdf", domain_name: "www.tekritisoftware.com")
Bookmark.create!(name: "Thinkdiff.net - geeky stuff, facebook, twitter, linkedin, php, mysql, web development, tips and more", url: "http://thinkdiff.net/", domain_name: "thinkdiff.net")
Bookmark.create!(name: "research.ijcaonline.org/volume37/number8/pxc3876667.pdf", url: "http://research.ijcaonline.org/volume37/number8/pxc3876667.pdf", domain_name: "research.ijcaonline.org")
Bookmark.create!(name: "ICASSP 2012 | 2012 IEEE International Conference on Acoustics, Speech, and Signal Processing | March 25-30, 2012 | Kyoto, Japan", url: "http://www.icassp2012.com/Papers.asp", domain_name: "www.icassp2012.com")
Bookmark.create!(name: "aodv opnet下修改 路由协议，将min hop routing 改为min cost ，附说明文档 Other systems 其他 161万源代码下载- www.pudn.com", url: "http://www.pudn.com/downloads206/sourcecode/others/detail972225.html", domain_name: "www.pudn.com")
Bookmark.create!(name: "teachers.ksu.edu.tw/rscheng/simulation/aodv_dump-110317.pdf", url: "http://teachers.ksu.edu.tw/rscheng/simulation/aodv_dump-110317.pdf", domain_name: "teachers.ksu.edu.tw")
Bookmark.create!(name: "WWDC 2012 Live 轉播 @ Panda's blog :: 痞客邦 PIXNET ::", url: "http://jon6773.pixnet.net/blog/post/36743472-wwdc-2012-live", domain_name: "jon6773.pixnet.net")
Bookmark.create!(name: "PChome線上購物 - 24h 購物《宇帷 AVEXIR Apple專用 16GB(8GBx2) DDR3 1333 筆記型記憶體》", url: "http://shopping.pchome.com.tw/?mod=item&func=exhibit&IT_NO=DRAC3H-A61954313&SR_NO=DRAC3J&ROWNO=2", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "2012欧洲杯直播-QQ欧洲杯直播-2012年欧锦赛QQ高清直播地址", url: "http://www.5xtiyu.com/ouzhoubeiqq.htm", domain_name: "www.5xtiyu.com")
Bookmark.create!(name: "NTCIR 9 Table of Contents", url: "http://research.nii.ac.jp/ntcir/workshop/OnlineProceedings9/NTCIR/", domain_name: "research.nii.ac.jp")
Bookmark.create!(name: "丹麦vs葡萄牙 腾讯体育", url: "http://zhibo.sports.qq.com/sports/3971/index.html", domain_name: "zhibo.sports.qq.com")
Bookmark.create!(name: "www.cs.nccu.edu.tw/~d10003/d10003.pdf", url: "http://www.cs.nccu.edu.tw/~d10003/d10003.pdf", domain_name: "www.cs.nccu.edu.tw")
Bookmark.create!(name: "Ruby on Rails Tutorial: Learn Rails by Example book and screencasts by Michael Hartl", url: "http://ruby.railstutorial.org/ruby-on-rails-tutorial-book", domain_name: "ruby.railstutorial.org")
Bookmark.create!(name: "PGM 读书笔记节选（十） « demonstrate 的 blog", url: "http://remonstrate.wordpress.com/2012/06/13/pgm-%e8%af%bb%e4%b9%a6%e7%ac%94%e8%ae%b0%e8%8a%82%e9%80%89%ef%bc%88%e5%8d%81%ef%bc%89/comment-page-1/#comment-1562", domain_name: "remonstrate.wordpress.com")
Bookmark.create!(name: "CSIE Communications", url: "http://csiecomm.blogspot.tw/", domain_name: "csiecomm.blogspot.tw")
Bookmark.create!(name: "PanSci 泛科學 | Blog | [真相是殘酷的]科學論文中20個常見句子的真正意義", url: "http://pansci.tw/archives/11681", domain_name: "pansci.tw")
Bookmark.create!(name: "Rails 101 | Rails 101 - 火速學會 Ruby on Rails", url: "http://rails-101.logdown.com/", domain_name: "rails-101.logdown.com")
Bookmark.create!(name: "Euro 2012: Cristiano Ronaldo lifts Portugal | Live football and soccer news | ESPNFC.com", url: "http://espnfc.com/us/en/news/1111314/cristiano-ronaldo-lifts-portugal-win.html", domain_name: "espnfc.com")
Bookmark.create!(name: "快播Qvod《纳德和西敏：一次别离/分居风暴》第1集綫上播放中 - 劇情片 - 台灣電影網", url: "http://www.tw116.com/vod-play-id-40035-sid-0-pid-0.html", domain_name: "www.tw116.com")
Bookmark.create!(name: "Downloads (2011-2012 Fall) | CS 193P iPhone Application Development", url: "http://www.stanford.edu/class/cs193p/cgi-bin/drupal/downloads-2011-fall", domain_name: "www.stanford.edu")
Bookmark.create!(name: "海灘的那一天 About Elly -- @movies【開眼電影】 @movies http://www.atmovies.com.tw", url: "http://app.atmovies.com.tw/movie/movie.cfm?action=filmdata&film_id=fair41360860", domain_name: "app.atmovies.com.tw")
Bookmark.create!(name: "NS2: How to add new routing protocol | Elmurod A. Talipov", url: "http://elmurod.net/index.php/2010/01/20/how-to-add-new-routing-protocol-in-ns2/", domain_name: "elmurod.net")
Bookmark.create!(name: "《新福尔摩斯/神探夏洛克》快播Qvod全集高清在線觀看 - 歐美剧 - 台灣電影網", url: "http://www.tw116.com/occident/xinfuermosishentanxialuoke/", domain_name: "www.tw116.com")
Bookmark.create!(name: "快播Qvod《蜘蛛侠3(QMV)》QMV高清綫上播放中 - 科幻片 - 台灣電影網", url: "http://www.tw116.com/vod-play-id-41517-sid-0-pid-0.html", domain_name: "www.tw116.com")
Bookmark.create!(name: "午夜三點的神秘出口 :: 痞客邦 PIXNET ::", url: "http://oftenshine.pixnet.net/blog", domain_name: "oftenshine.pixnet.net")
Bookmark.create!(name: "Dcard", url: "http://dcard.tw/index.php", domain_name: "dcard.tw")
Bookmark.create!(name: "百家爭鳴－新興無線影音技術評析", url: "http://mic.iii.org.tw/aisp/reports/reportdetail_register.asp?docid=2934&rtype=freereport", domain_name: "mic.iii.org.tw")
Bookmark.create!(name: "活動訊息", url: "http://www.communications.org.tw/communications/getdetail.php?n_unit=3803&cfz_unit=3&cf_unit=14&menu=1", domain_name: "www.communications.org.tw")
Bookmark.create!(name: "IEEE Xplore - Speech and Audio Processing, IEEE Transactions on", url: "http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=89", domain_name: "ieeexplore.ieee.org")
Bookmark.create!(name: "IEEE Xplore - Signal Processing Magazine, IEEE", url: "http://ieeexplore.ieee.org/xpl/tocresult.jsp?isnumber=6179795&punumber=79", domain_name: "ieeexplore.ieee.org")
Bookmark.create!(name: "www.twtik.org/tik/attachments/067_D-03.pdf", url: "http://www.twtik.org/tik/attachments/067_D-03.pdf", domain_name: "www.twtik.org")
Bookmark.create!(name: "mpac.ee.ntu.edu.tw/~nh928/main_data/CommLab7.pdf", url: "http://mpac.ee.ntu.edu.tw/~nh928/main_data/CommLab7.pdf", domain_name: "mpac.ee.ntu.edu.tw")
Bookmark.create!(name: "Thank You for Purchasing DisplayFusion Pro! | DisplayFusion by Binary Fortress Software", url: "http://www.displayfusion.com/Purchase/ThankYou/?ID=caf4f07d-22b2-4178-8b01-a128e654e3a6", domain_name: "www.displayfusion.com")
Bookmark.create!(name: "筆耕歲月: 給電子電機人的建議", url: "http://wh012027.blogspot.com/2010/01/blog-post_31.html", domain_name: "wh012027.blogspot.com")
Bookmark.create!(name: "交資夢想 | 交大資工，交織夢想。", url: "http://nctucs.wordpress.com/", domain_name: "nctucs.wordpress.com")
Bookmark.create!(name: "留學：SOP解析 -- 2009/5/9更新 @ 倫倫的小blog :: 痞客邦 PIXNET ::", url: "http://xination.pixnet.net/blog/post/21739595", domain_name: "xination.pixnet.net")
Bookmark.create!(name: "靜謐。在灰藍天空下 - MIT，我的生活紀錄 [每個第一次]", url: "http://www.wretch.cc/blog/eggchi/11932028", domain_name: "www.wretch.cc")
Bookmark.create!(name: "1個月上美國名校！ - 文章分類: 一個月內讓你申請上美國名校！", url: "http://www.wretch.cc/blog/HenryLiu&category_id=8422659", domain_name: "www.wretch.cc")
Bookmark.create!(name: "Grad2011 • 別讓面試毀了你 (電話面試適用)", url: "http://graduate2011.tumblr.com/post/3340390473", domain_name: "graduate2011.tumblr.com")
Bookmark.create!(name: "Backbone.js", url: "http://backbonejs.org/#Model-changedAttributes", domain_name: "backbonejs.org")
Bookmark.create!(name: "Underscore Reference — Smooth CoffeeScript", url: "http://autotelicum.github.com/Smooth-CoffeeScript/literate/underscore.html", domain_name: "autotelicum.github.com")
Bookmark.create!(name: "MiiSoo開發日誌: Javascript 字串處理 (String Operations)", url: "http://miisoo.blogspot.tw/2008/01/javascript-string-operations.html", domain_name: "miisoo.blogspot.tw")
Bookmark.create!(name: "Machine Learning", url: "http://www.ml-class.org/course/class/index", domain_name: "www.ml-class.org")
Bookmark.create!(name: "UC Berkeley Webcasts | Video and Podcasts:", url: "http://webcast.berkeley.edu/playlist#c,d,Computer_Science,3A5075EC94726781", domain_name: "webcast.berkeley.edu")
Bookmark.create!(name: "Spoken Content Retrieval - Lattices and Beyond - Invited Speakers | SuperLectures.com", url: "http://www.superlectures.com/asru2011/lecture.php?lang=en&id=5", domain_name: "www.superlectures.com")
Bookmark.create!(name: "哈佛大学公开课：幸福课_全23集_中文字幕更新至第23集_网易公开课_网易视频", url: "http://v.163.com/special/positivepsychology/", domain_name: "v.163.com")
Bookmark.create!(name: "Automata", url: "https://class.coursera.org/automata/class/index", domain_name: "class.coursera.org")
Bookmark.create!(name: "Coursera", url: "https://www.coursera.org/", domain_name: "www.coursera.org")
Bookmark.create!(name: "Machine Learning", url: "https://class.coursera.org/ml/class/index", domain_name: "class.coursera.org")
Bookmark.create!(name: "Introduction to Databases", url: "http://www.db-class.org/course/class/index", domain_name: "www.db-class.org")
Bookmark.create!(name: "SaaS", url: "https://class.coursera.org/saas-2012-003/lecture/index", domain_name: "class.coursera.org")
Bookmark.create!(name: "臺大電機之友 第三十二期 學思歷程中的點點滴滴 / 洪士灝", url: "http://alumni.ee.ntu.edu.tw/wp/content/32/6.html", domain_name: "alumni.ee.ntu.edu.tw")
Bookmark.create!(name: "台大資工 陳彥仰教授 - Prof. Mike Chen @ National Taiwan University", url: "http://mikechen.com/", domain_name: "mikechen.com")
Bookmark.create!(name: "Chun-Ju Lai's Personal Page", url: "http://www2.ee.ntu.edu.tw/~b94901110/", domain_name: "www2.ee.ntu.edu.tw")
Bookmark.create!(name: "Amazon.com: Art of Computer Programming, Volume 1: Fundamental Algorithms (3rd Edition) (0785342896831): Donald E. Knuth: Books", url: "http://www.amazon.com/Art-Computer-Programming-Fundamental-Algorithms/dp/0201896834", domain_name: "www.amazon.com")
Bookmark.create!(name: "巨擘書局 - 專業經營Textbooks、原文書、英文教科書、西書、中譯本, 網路書店, 網路書局.", url: "http://apexbook.tw/", domain_name: "apexbook.tw")
Bookmark.create!(name: "天瓏網路書店 | Fundamentals of Data Structures in C++, 2/e", url: "http://www.tenlong.com.tw/items/0929306376?item_id=31054", domain_name: "www.tenlong.com.tw")
Bookmark.create!(name: "博客來", url: "http://www.books.com.tw/", domain_name: "www.books.com.tw")
Bookmark.create!(name: "博客來3C館>DICOTA Dee Messenger 都會休閒14.1電腦側背包(典雅灰)", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000115287", domain_name: "www.books.com.tw")
Bookmark.create!(name: "博客來3C館>DICOTA Dee Messenger 都會休閒14.1電腦側背包(蘋果綠)", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000115286", domain_name: "www.books.com.tw")
Bookmark.create!(name: "博客來3C館>蒙恬 Q Pen全彈性電容性觸控筆(黑)", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000231410", domain_name: "www.books.com.tw")
Bookmark.create!(name: "PChome線上購物 - 時尚購物《【Kawasaki】超輕時尚_14吋電腦公事包(大)_橘色》", url: "http://shopping.pchome.com.tw/?mod=item&func=exhibit&IT_NO=BCAX78-A45892891&SR_NO=BBBE1N&ROWNO=30", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "Zakka雜貨網: 帆布NB郵差包-藍+橘", url: "http://www.zakka.com.tw/product/HL03702", domain_name: "www.zakka.com.tw")
Bookmark.create!(name: "PChome線上購物 - 生活《【德國 TATONKA 】Fivefourty 超行動力 都會休閒側背包《TA1774》》", url: "http://shopping.pchome.com.tw/?mod=item&func=exhibit&IT_NO=CEAC1F-A25635632&SR_NO=CEACC4&ROWNO=18", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "Osprey FlapJack Courier 男用單肩電腦郵差包 白", url: "http://100mountain.com/shop/index.php?route=product/product&manufacturer_id=231&product_id=5551", domain_name: "100mountain.com")
Bookmark.create!(name: "Osprey FlapJack Courier 男用單肩電腦郵差包 黑", url: "http://100mountain.com/shop/index.php?route=product/product&manufacturer_id=231&product_id=5550", domain_name: "100mountain.com")
Bookmark.create!(name: "PChome線上購物 - 24h 購物《STM Slim系列筆電包-for MacBook 11吋(XS)》", url: "http://shopping.pchome.com.tw/DGAX0N-A54560091", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "MacBook Pro 適用的 15 吋 Incase 尼龍保護袋 - Apple Store (Taiwan)", url: "http://store.apple.com/tw/product/H5013PA/A?fnode=MTY1NDA2Ng&s=topSellers", domain_name: "store.apple.com")
Bookmark.create!(name: "Protective Sleeve Deluxe for 13\" MacBook Pro by Incase", url: "http://goincase.com/products/detail/protective-sleeve-deluxe-cl57486/5", domain_name: "goincase.com")
Bookmark.create!(name: "PChome Online 商店街 - 敗家網 - Booq Boa Nerve Messenger 電腦側背包(信差包) - L", url: "http://www.pcstore.com.tw/byja/M04381643.htm", domain_name: "www.pcstore.com.tw")
Bookmark.create!(name: "博客來3C館>鐵三角Audio-Technica ATH-CP500 MC粉紅 耳掛式運動耳機 讓我陪你運動吧！", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000217088", domain_name: "www.books.com.tw")
Bookmark.create!(name: "博客來3C館>鐵三角Audio-Technica ATH-EQ500 BL 藍色 繽紛彩色耳掛耳機", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000227813", domain_name: "www.books.com.tw")
Bookmark.create!(name: "PChome線上購物 - 24h 購物《愛樂活日式多功能桌上架(白)》", url: "http://shopping.pchome.com.tw/?mod=item&func=exhibit&IT_NO=DEAB2B-A58433519&SR_NO=DCADFT&ROWNO=1", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "PChome線上購物 - 24h 購物《HP 564XL 原廠墨水匣超值組合包(2黑3彩)》", url: "http://shopping.pchome.com.tw/?mod=item&func=exhibit&IT_NO=DCAF03-146858450&SR_NO=DCAF03&ROWNO=45", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "博客來3C館>SONY 藍芽無線立體聲耳機麥克風(DR-BT21G)", url: "http://www.books.com.tw/exep/prod/newprod_file.php?item=N000155580", domain_name: "www.books.com.tw")
Bookmark.create!(name: "PChome線上購物 - 24h 購物《PANASONIC 輕巧型電動修鼻毛器ER-GN10-K》", url: "http://shopping.pchome.com.tw/DMAH05-A50756007", domain_name: "shopping.pchome.com.tw")
Bookmark.create!(name: "《反恐24小时第1季》快播Qvod全集高清線上观看 - 歐美剧 - 台灣電影網", url: "http://www.tw116.com/vod-read-id-12725.html", domain_name: "www.tw116.com")
Bookmark.create!(name: "The Art of Clean Up: Sorting and Stacking Everyday Objects | Jeannie Huang", url: "http://www.jeanniejeannie.com/2011/08/29/the-art-of-clean-up-sorting-and-stacking-everyday-objects/", domain_name: "www.jeanniejeannie.com")
Bookmark.create!(name: "YouTube - ‪神奇汽車廣告‬‏", url: "http://www.youtube.com/watch?v=dOD_lCT6ro4", domain_name: "www.youtube.com")
Bookmark.create!(name: "1997年think different廣告，賈伯斯的配音(中文翻譯） @ 李昆霖前遛鳥國手 :: 痞客邦 PIXNET ::", url: "http://kunlinjohnlee.pixnet.net/blog/post/29235584", domain_name: "kunlinjohnlee.pixnet.net")
Bookmark.create!(name: "溫度 - YouTube", url: "http://www.youtube.com/watch?feature=player_embedded&v=oKprC9XQAS0#!", domain_name: "www.youtube.com")
Bookmark.create!(name: "《反恐24小时第2季》快播Qvod全集高清線上观看 - 歐美剧 - 台灣電影網", url: "http://www.tw116.com/vod-read-id-948.html", domain_name: "www.tw116.com")
Bookmark.create!(name: "快播Qvod《反恐24小时第3季》第1集綫上播放中 - 歐美剧 - 台灣電影網", url: "http://www.tw116.com/vod-play-id-949-sid-0-pid-0.html", domain_name: "www.tw116.com")
Bookmark.create!(name: "快播Qvod《无敌浩克/神奇绿巨人[BD无水印]》第1集綫上播放中 - 科幻片 - 台灣電影網", url: "http://tw116.com/vod-play-id-15923-sid-0-pid-0.html", domain_name: "tw116.com")
Bookmark.create!(name: "《冰与火之歌：权力的游戏第一季》快播Qvod全集高清在線觀看 - 歐美剧 - 台灣電影網", url: "http://www.tw116.com/occident/bingyuhuozhigequanlideyouxidiyiji/", domain_name: "www.tw116.com")
Bookmark.create!(name: "網路測速中心", url: "http://www.ascc.sinica.edu.tw/iascc/netsrv/speed/", domain_name: "www.ascc.sinica.edu.tw")
Bookmark.create!(name: "大魔術師 - Google 搜尋", url: "https://www.google.com/search?sugexp=chrome,mod=10&sourceid=chrome&ie=UTF-8&q=%E5%A4%A7%E9%AD%94%E8%A1%93%E5%B8%AB", domain_name: "www.google.com")
Bookmark.create!(name: "嘎名人學台語第1集-蔡阿嘎X喬喬(于卉喬)：來跟喬喬學喜怒哀樂的台語吧 - YouTube", url: "http://www.youtube.com/watch?v=cTdqc4lXjws", domain_name: "www.youtube.com")
Bookmark.create!(name: "A Thousand Miles - Vanessa Carlton (Boyce Avenue feat. Alex Goot acoustic cover) on iTunes - YouTube", url: "http://www.youtube.com/watch?v=h297vLkHijQ&feature=related", domain_name: "www.youtube.com")
Bookmark.create!(name: "TechOrange | 科技報橘", url: "http://techorange.com/", domain_name: "techorange.com")
Bookmark.create!(name: "MATLAB 之工程應用", url: "http://bime-matlab.blogspot.com/", domain_name: "bime-matlab.blogspot.com")
Bookmark.create!(name: "{\large\it 「計算機應用 (II)」這門課的對象是大一工科同學，希望讓同學了解}", url: "http://webclass.ncu.edu.tw/~junwu/index.html", domain_name: "webclass.ncu.edu.tw")
Bookmark.create!(name: "演算法筆記", url: "http://www.csie.ntnu.edu.tw/~u91029/index.html", domain_name: "www.csie.ntnu.edu.tw")
Bookmark.create!(name: "Welcome to MyStudy", url: "http://www.mystudy.com.tw/", domain_name: "www.mystudy.com.tw")
Bookmark.create!(name: "Engadget 中文版", url: "http://chinese.engadget.com/page/2/", domain_name: "chinese.engadget.com")
Bookmark.create!(name: "GPS Visualizer: Assign elevation data to coordinates", url: "http://www.gpsvisualizer.com/elevation", domain_name: "www.gpsvisualizer.com")
Bookmark.create!(name: "Octave note", url: "http://irw.ncut.edu.tw/peterju/octave.html", domain_name: "irw.ncut.edu.tw")
Bookmark.create!(name: "Appked - All About Share,All About Mac.", url: "http://appd.in/", domain_name: "appd.in")
Bookmark.create!(name: "Parallels Desktop 7.0.14920.689535 for Mac OSX | AppKed", url: "http://appd.in/parallels-desktop-7-0/", domain_name: "appd.in")
Bookmark.create!(name: "[Mac] Parallels Desktop 7的一些注意事項 | Life[\"Breathing\"]", url: "http://blog.hsin.tw/2011/mac-parallels-desktop-7-notice/", domain_name: "blog.hsin.tw")
Bookmark.create!(name: "MacUknow | 蘋果中文知識網", url: "http://macuknow.com/", domain_name: "macuknow.com")
Bookmark.create!(name: "[開箱] 新入手玩具KeePad-有iPad跟無線鍵盤的朋友注意囉～ | MacUknow", url: "http://macuknow.com/node/15004", domain_name: "macuknow.com")
Bookmark.create!(name: "快播Qvod《反恐24小时第7季》第2集綫上播放中 - 歐美剧 - 台灣電影網", url: "http://tw116.com/vod-play-id-14586-sid-0-pid-1.html", domain_name: "tw116.com")
Bookmark.create!(name: "強打推薦文章 | 線代啟示錄", url: "http://ccjou.wordpress.com/%E9%96%B1%E8%AE%80%E5%B0%8E%E5%BC%95/%E5%BC%B7%E6%89%93%E6%8E%A8%E8%96%A6%E6%96%87%E7%AB%A0/", domain_name: "ccjou.wordpress.com")
Bookmark.create!(name: "www.math.mtu.edu/~kreher/cages/pseudocode/pseudocode.pdf", url: "http://www.math.mtu.edu/~kreher/cages/pseudocode/pseudocode.pdf", domain_name: "www.math.mtu.edu")
Bookmark.create!(name: "http://ftp.cs.pu.edu.tw/pub/CTAN/info/visualFAQ/visualFAQ.pdf", url: "http://ftp.cs.pu.edu.tw/pub/CTAN/info/visualFAQ/visualFAQ.pdf", domain_name: "ftp.cs.pu.edu.tw")
Bookmark.create!(name: "Edward G.J. Lee's Note, 果正札記", url: "http://cle.linux.org.tw/~edt1023/", domain_name: "cle.linux.org.tw")
Bookmark.create!(name: "cwtex-install", url: "http://homepage.ntu.edu.tw/~ntut019/cwtex-install/cwtex-install.html", domain_name: "homepage.ntu.edu.tw")
Bookmark.create!(name: "《反恐24小时第8季》快播Qvod全集高清線上观看 - 歐美剧 - 台灣電影網", url: "http://tw116.com/occident/fankong24xiaoshidi8ji/", domain_name: "tw116.com")
Bookmark.create!(name: "[筆記] gcc參數指令(轉錄) @ [FGISC。Nanro] 未來開端 :: 痞客邦 PIXNET ::", url: "http://aikosenoo.pixnet.net/blog/post/23038692-[%E7%AD%86%E8%A8%98]-gcc%E5%8F%83%E6%95%B8%E6%8C%87%E4%BB%A4(%E8%BD%89%E9%8C%84)", domain_name: "aikosenoo.pixnet.net")
Bookmark.create!(name: "《妙警贼探/不是冤家不聚头/猫鼠游戏第3季》快播Qvod全集高清線上观看 - 歐美剧 - 台灣電影網", url: "http://tw116.com/occident/miaojingzeitanbushiyuanjiabujutoumiaoshuyouxidi3ji/", domain_name: "tw116.com")
Bookmark.create!(name: "MacBookPro8-2/Oneiric - Community Ubuntu Documentation", url: "https://help.ubuntu.com/community/MacBookPro8-2/Oneiric", domain_name: "help.ubuntu.com")
Bookmark.create!(name: "《反恐24小时第5季》快播Qvod全集高清線上观看 - 歐美剧 - 台灣電影網", url: "http://tw116.com/occident/fankong24xiaoshidi5ji/", domain_name: "tw116.com")
Bookmark.create!(name: "追求神乎其技的程式設計之道（十） | vgod's blog", url: "http://blog.vgod.tw/2009/12/18/divine-code-10/", domain_name: "blog.vgod.tw")
Bookmark.create!(name: "mac版Adobe CS6破解文件 | 心若红叶", url: "http://001.net76.net/adobe-cs6-crack-for-mac.html", domain_name: "001.net76.net")
Bookmark.create!(name: "Abstract Algebra I - Rough Guides to Mathematics", url: "http://mathroughguides.wikidot.com/article:abstract-algebra-i", domain_name: "mathroughguides.wikidot.com")
Bookmark.create!(name: "www.glump.net/content/abstract_algebra_cheat/index.pdf", url: "http://www.glump.net/content/abstract_algebra_cheat/index.pdf", domain_name: "www.glump.net")
Bookmark.create!(name: "iPAD iPHONE PROGRAMMING: Assignment 2 Required Task 4 - Stanford University Open Course CS193P Solution", url: "http://ipadiphoneprogramming.blogspot.tw/2012/03/assignment-2-required-task-4-stanford.html", domain_name: "ipadiphoneprogramming.blogspot.tw")
Bookmark.create!(name: "玩遊戲懂\"溯因邏輯創新法\"! --- 維京人酒吧 Viking Bar", url: "http://viking-bar.blogspot.tw/2012/07/blog-post_17.html", domain_name: "viking-bar.blogspot.tw")
Bookmark.create!(name: "回歸最純粹的", url: "http://www.wretch.cc/blog/raphael0914", domain_name: "www.wretch.cc")
Bookmark.create!(name: "無名挖挖挖", url: "http://mining.tw/", domain_name: "mining.tw")
Bookmark.create!(name: "回歸最純粹的", url: "http://raphael0914.blogspot.com/", domain_name: "raphael0914.blogspot.com")
Bookmark.create!(name: "Blogger", url: "http://www.blogger.com/home", domain_name: "www.blogger.com")
Bookmark.create!(name: "Plurk", url: "http://www.plurk.com/rf0914", domain_name: "www.plurk.com")
Bookmark.create!(name: "GO!!! - 網誌 - yam天空部落", url: "http://blog.yam.com/raphael0914", domain_name: "blog.yam.com")
Bookmark.create!(name: "raphael", url: "http://raphael0914.pixnet.net/blog", domain_name: "raphael0914.pixnet.net")
Bookmark.create!(name: "創業必讀 » MR JAMIE", url: "http://mrjamie.cc/entrepreneurs/", domain_name: "mrjamie.cc")
Bookmark.create!(name: "大學部電子電路實驗一", url: "http://cktlab.ee.ntu.edu.tw/2010/", domain_name: "cktlab.ee.ntu.edu.tw")
Bookmark.create!(name: "電路學", url: "http://cktlab.ee.ntu.edu.tw/ckts2010fall/", domain_name: "cktlab.ee.ntu.edu.tw")
Bookmark.create!(name: "微分方程", url: "http://cc.ee.ntu.edu.tw/~twhuang/pa/?C=D;O=A", domain_name: "cc.ee.ntu.edu.tw")
Bookmark.create!(name: "交換電路與邏輯設計", url: "http://homepage.ntu.edu.tw/~r98942048/ld2010fall/", domain_name: "homepage.ntu.edu.tw")
Bookmark.create!(name: "交換電路與邏輯設計", url: "https://ceiba.ntu.edu.tw/course/4eefbd/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "電路學", url: "https://ceiba.ntu.edu.tw/course/a0a63e/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "計算機程式", url: "https://ceiba.ntu.edu.tw/course/abb057/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "服務學習", url: "https://ceiba.ntu.edu.tw/course/00416e/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "人權的理論與實際", url: "https://ceiba.ntu.edu.tw/course/9b893d/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "憲政體制與民主發展", url: "https://ceiba.ntu.edu.tw/course/e0c5cf/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "交換電路與邏輯設計 2010 年秋季班", url: "http://homepage.ntu.edu.tw/~r98942048/ld2010fall/", domain_name: "homepage.ntu.edu.tw")
Bookmark.create!(name: "電路學 2010 年秋季班", url: "http://cktlab.ee.ntu.edu.tw/ckts2010fall/", domain_name: "cktlab.ee.ntu.edu.tw")
Bookmark.create!(name: "電子電路實驗二", url: "http://eelab.ee.ntu.edu.tw/info.htm", domain_name: "eelab.ee.ntu.edu.tw")
Bookmark.create!(name: "線性代數", url: "http://cc.ee.ntu.edu.tw/~tomme/LA/LA_EE.html", domain_name: "cc.ee.ntu.edu.tw")
Bookmark.create!(name: "信號與系統", url: "http://cktlab.ee.ntu.edu.tw/ss2011spring/", domain_name: "cktlab.ee.ntu.edu.tw")
Bookmark.create!(name: "Linear Algebra (901 10030), Spring 2007, NTUEE", url: "http://cc.ee.ntu.edu.tw/class/linear-algebra/", domain_name: "cc.ee.ntu.edu.tw")
Bookmark.create!(name: "BJ ONLINE", url: "http://140.112.41.110/prob/index.php", domain_name: "140.112.41.110")
Bookmark.create!(name: "Probability and Statistics (Spring, 2011)", url: "https://sites.google.com/site/ntueepas/", domain_name: "sites.google.com")
Bookmark.create!(name: "機率與統計", url: "https://ceiba.ntu.edu.tw/course/e121dd/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "複變", url: "https://ceiba.ntu.edu.tw/course/64e1bc/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "中國傳統法律、文化與社會 (暑二)", url: "https://ceiba.ntu.edu.tw/course/c251a3/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "資料結構與程式設計", url: "https://ceiba.ntu.edu.tw/course/905a4e/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "控制系統", url: "https://ceiba.ntu.edu.tw/course/630343/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "國文上", url: "https://ceiba.ntu.edu.tw/course/982bbd/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "積體電路設計", url: "https://ceiba.ntu.edu.tw/course/e72a2b/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "IC設計實驗室可供連線工作站一覽表", url: "http://cad.ee.ntu.edu.tw/ws_list.htm", domain_name: "cad.ee.ntu.edu.tw")
Bookmark.create!(name: "數位語音處理概論", url: "https://ceiba.ntu.edu.tw/course/b47ca3/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "Welcome to Speech Lab", url: "http://speech.csie.ntu.edu.tw/previous_version/index.htm", domain_name: "speech.csie.ntu.edu.tw")
Bookmark.create!(name: "Speech Lab - courses", url: "http://speech.ee.ntu.edu.tw/courses/Project2011spring/", domain_name: "speech.ee.ntu.edu.tw")
Bookmark.create!(name: "Speech Lab - courses", url: "http://speech.ee.ntu.edu.tw/courses/DSP2011Autumn/", domain_name: "speech.ee.ntu.edu.tw")
Bookmark.create!(name: "電子電路實驗三", url: "http://eelab.ee.ntu.edu.tw/mcl3.htm", domain_name: "eelab.ee.ntu.edu.tw")
Bookmark.create!(name: "NTNU Speech Recognition Course", url: "http://berlin.csie.ntnu.edu.tw/Courses/Speech%20Recognition/Speech%20Recognition_Main_2011F.htm", domain_name: "berlin.csie.ntnu.edu.tw")
Bookmark.create!(name: "【易文言】-古文,文言文在线翻译网|文言文大全|文言文阅读|古文观止|国学|古文字典|文言文字典|古汉语词典|孟子|论语|庄子|诗经|史记|战国策|资治通鉴|荀子|老子|左传|尚书|汉书|周易|大学|中", url: "http://www.ewenyan.com/#zz", domain_name: "www.ewenyan.com")
Bookmark.create!(name: "Ruby-Doc.org", url: "http://ruby-doc.org/", domain_name: "ruby-doc.org")
Bookmark.create!(name: "Uploading Files to S3 in Rails with Paperclip | Heroku Dev Center", url: "https://devcenter.heroku.com/articles/uploading-files-s3-rails-paperclip", domain_name: "devcenter.heroku.com")
Bookmark.create!(name: "ActiveRecord::Migration", url: "http://api.rubyonrails.org/classes/ActiveRecord/Migration.html", domain_name: "api.rubyonrails.org")
Bookmark.create!(name: "ActionController::Responder", url: "http://api.rubyonrails.org/classes/ActionController/Responder.html", domain_name: "api.rubyonrails.org")
Bookmark.create!(name: "[430]新進成員SOP 及注意事項 - Google 文件", url: "https://docs.google.com/document/d/1KLoguvXiV7OKoJTjRCaaEgWx9OQK0uHU0RKdzIxLY2Y/edit?pli=1", domain_name: "docs.google.com")
Bookmark.create!(name: "[430] Research Meeting List - Google 文件", url: "https://docs.google.com/spreadsheet/ccc?key=0AovpoMoDP_f8dFVJV2JVckVpNURONy1tN2J2LWVYTVE#gid=0", domain_name: "docs.google.com")
Bookmark.create!(name: "Prezi - The Zooming Presentation Editor", url: "http://prezi.com/", domain_name: "prezi.com")
Bookmark.create!(name: "Monitoring Progress of a Calculation | Loren on the Art of MATLAB", url: "http://blogs.mathworks.com/loren/2007/08/01/monitoring-progress-of-a-calculation/#7", domain_name: "blogs.mathworks.com")
Bookmark.create!(name: "Customize.org - Download Themes, Skins, Wallpapers and Icons for Windows from the original skin site!", url: "http://customize.org/", domain_name: "customize.org")
Bookmark.create!(name: "【作品試聽】安妮朵拉 - 人生最大的意義 - YouTube", url: "http://www.youtube.com/watch?v=q7ydHX2_1yg&feature=share", domain_name: "www.youtube.com")
Bookmark.create!(name: "五月天溫柔MV - YouTube", url: "http://www.youtube.com/watch?v=EwCtKDvVS9g&feature=related", domain_name: "www.youtube.com")
Bookmark.create!(name: "亞洲小天后蔡依林獻聲上海世博會台灣館主題曲「台灣的心跳聲」 MV完整版 - YouTube", url: "http://www.youtube.com/watch?v=uNXS9y-QY04", domain_name: "www.youtube.com")
Bookmark.create!(name: "带我走 ktv MV (high quality) - 杨丞琳 - YouTube", url: "http://www.youtube.com/watch?v=CpFgeI-c7_s&feature=related", domain_name: "www.youtube.com")
Bookmark.create!(name: "Advances in Wireless LANS", url: "http://www.slideshare.net/allabout4g/advances-in-wireless-lans", domain_name: "www.slideshare.net")
Bookmark.create!(name: "Wi-Fi, WirelessHD Cozy up to WiGig Standard | PCWorld", url: "http://www.pcworld.com/article/195914/wifi_wirelesshd_cozy_up_to_wigig_standard.html", domain_name: "www.pcworld.com")
Bookmark.create!(name: "WiGig Fast Wireless May Change Wi-Fi, Home Networks | PCWorld", url: "http://www.pcworld.com/article/164716/wigig_fast_wireless_may_change_wifi_home_networks.html", domain_name: "www.pcworld.com")
Bookmark.create!(name: "解析無線局域網Wi-Fi技術標準——802.11ad - 【電信 & IT】New Vision - Yahoo!奇摩部落格", url: "http://tw.myblog.yahoo.com/jw!9EJiHLKAHxVSpfxCMm2qVDDHATEq1w--/article?mid=-2&prev=819&l=f&fid=48", domain_name: "tw.myblog.yahoo.com")
Bookmark.create!(name: "www.ee.nthu.edu.tw/~jtchen/com5128/project_old/project1.pdf", url: "http://www.ee.nthu.edu.tw/~jtchen/com5128/project_old/project1.pdf", domain_name: "www.ee.nthu.edu.tw")
Bookmark.create!(name: "產業策略評析：WiGig無線千兆聯盟，制定新一代無線LAN標準", url: "http://cdnet.stpi.org.tw/techroom/analysis/2009/pat_09_A016.htm", domain_name: "cdnet.stpi.org.tw")
Bookmark.create!(name: "大頻寬特性誰與爭鋒 60GHz實現高頻影音傳輸 - 技術前瞻 - 新通訊元件雜誌", url: "http://www.2cm.com.tw/technologyshow_content.asp?sn=1201190008", domain_name: "www.2cm.com.tw")
Bookmark.create!(name: "www.etsi.org/deliver/etsi_tr/102500_102599/102555/01.01.01_60/tr_102555v010101p.pdf", url: "http://www.etsi.org/deliver/etsi_tr/102500_102599/102555/01.01.01_60/tr_102555v010101p.pdf", domain_name: "www.etsi.org")
Bookmark.create!(name: "vp.ntu.edu.tw/effort971103ppt.pdf", url: "http://vp.ntu.edu.tw/effort971103ppt.pdf", domain_name: "vp.ntu.edu.tw")
Bookmark.create!(name: "www.cteccb.org.tw/pdf/IECQ-48-7.pdf", url: "http://www.cteccb.org.tw/pdf/IECQ-48-7.pdf", domain_name: "www.cteccb.org.tw")
Bookmark.create!(name: "Error Control Coding Fundamentals and Applications", url: "http://it.scribd.com/doc/7299932/Error-Control-Coding-Fundamentals-and-Applications", domain_name: "it.scribd.com")
Bookmark.create!(name: "Ruby on Rails Documentation", url: "http://api.rubyonrails.org/", domain_name: "api.rubyonrails.org")
Bookmark.create!(name: "Ruby on Rails - APIdock", url: "http://apidock.com/rails", domain_name: "apidock.com")
Bookmark.create!(name: "Rails Searchable API Doc", url: "http://railsapi.com/", domain_name: "railsapi.com")
Bookmark.create!(name: "ActiveRecord::ConnectionAdapters::SchemaStatements", url: "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-create_table", domain_name: "api.rubyonrails.org")
Bookmark.create!(name: "REST on Rails指南2：无穷尽的API", url: "http://www.letrails.cn/archives/8/", domain_name: "www.letrails.cn")
Bookmark.create!(name: "學Rails 3要看什麼書? - iT邦幫忙::IT知識分享社群", url: "http://ithelp.ithome.com.tw/question/10061401", domain_name: "ithelp.ithome.com.tw")
Bookmark.create!(name: "image upload rails paperclip - Google 搜尋", url: "https://www.google.com/search?hl=zh-TW&q=image+upload+rails+paperclip&oq=image+upload+rails+p&gs_l=serp.3.1.0i30l2j0i8i30l7.6126.6997.0.9167.2.2.0.0.0.0.26.51.2.2.0.ernk_fspiked_nsqb..0.0...1c.830WA-AvStI", domain_name: "www.google.com")
Bookmark.create!(name: "Building a Custom HTML5 Audio Player with jQuery « Neutron Creations", url: "http://neutroncreations.com/blog/building-a-custom-html5-audio-player-with-jquery/", domain_name: "neutroncreations.com")
Bookmark.create!(name: "Mozilla Developer Network", url: "https://developer.mozilla.org/zh-TW/", domain_name: "developer.mozilla.org")
Bookmark.create!(name: "JumpstartLab - We Build Developers", url: "http://jumpstartlab.com/", domain_name: "jumpstartlab.com")
Bookmark.create!(name: "陳彥仰教授 - YouTube", url: "http://www.youtube.com/watch?v=wbVKIdJ_15g&feature=youtu.be", domain_name: "www.youtube.com")
Bookmark.create!(name: "index3 - Minus", url: "http://minus.com/mAVDVaEWF/12", domain_name: "minus.com")
Bookmark.create!(name: "AM Design :: We Strut Your Stuff™ :: North Richland Hills", url: "http://www.amdesign.com/", domain_name: "www.amdesign.com")
Bookmark.create!(name: "Screenshots - CSS-Tricks", url: "http://css-tricks.com/gallery/", domain_name: "css-tricks.com")
Bookmark.create!(name: "jQuery UI - Autocomplete Demos & Documentation", url: "http://jqueryui.com/demos/autocomplete/", domain_name: "jqueryui.com")
Bookmark.create!(name: "jQuery UI 介紹 - 流星的隨筆記事~☆- 點部落", url: "http://www.dotblogs.com.tw/alonstar/archive/2010/04/17/14657.aspx", domain_name: "www.dotblogs.com.tw")
Bookmark.create!(name: "Basic multi-column · jQuery Masonry", url: "http://masonry.desandro.com/demos/basic-multi-column.html", domain_name: "masonry.desandro.com")
Bookmark.create!(name: "developer.apple.com/library/ios/DOCUMENTATION/UserExperience/Conceptual/MobileHIG/MobileHIG.pdf", url: "http://developer.apple.com/library/ios/DOCUMENTATION/UserExperience/Conceptual/MobileHIG/MobileHIG.pdf", domain_name: "developer.apple.com")
Bookmark.create!(name: "www.usabilitymax.com/wp-content/uploads/downloads/2011/11/iPhone-HIG.pdf", url: "http://www.usabilitymax.com/wp-content/uploads/downloads/2011/11/iPhone-HIG.pdf", domain_name: "www.usabilitymax.com")
Bookmark.create!(name: "50多個 Adobe Illustrator 圖示製作教學 | 設計•香港", url: "http://www.designerhk.com/blog/48/5878", domain_name: "www.designerhk.com")
Bookmark.create!(name: "Components · Twitter Bootstrap", url: "http://twitter.github.com/bootstrap/components.html#labels", domain_name: "twitter.github.com")
Bookmark.create!(name: "所有 Skill-MediaTools 分類的文章 第1頁 | demo小鋪", url: "http://demo.tc/List/Skill/MediaTools", domain_name: "demo.tc")
Bookmark.create!(name: "Blogs of Note", url: "http://blogsofnote.blogspot.tw/?view=snapshot", domain_name: "blogsofnote.blogspot.tw")
Bookmark.create!(name: "Fixed Floating Elements | jQuery for Designers - Tutorials and screencasts", url: "http://jqueryfordesigners.com/fixed-floating-elements/", domain_name: "jqueryfordesigners.com")
Bookmark.create!(name: "jquery floating fix - Google 搜尋", url: "https://www.google.com/search?hl=zh-TW&q=jquery+floating+fix&oq=jquery+floating+fix&gs_l=serp.3..0i19.5774.7548.0.8523.7.7.0.0.0.0.27.157.7.7.0...0.0...1c.O0XTdZ9UYss", domain_name: "www.google.com")
Bookmark.create!(name: "Javascript · Twitter Bootstrap", url: "http://twitter.github.com/bootstrap/javascript.html#dropdowns", domain_name: "twitter.github.com")
Bookmark.create!(name: "CSS3 Ribbons | css3教程-css3实例-css3动画 | W3CPlus", url: "http://www.w3cplus.com/css3/css3-ribbons", domain_name: "www.w3cplus.com")
Bookmark.create!(name: "css3 | 博客文章分类 | W3CPlus css3 | css3学习-css3教程-css3实例-css3动画 W3CPlus", url: "http://www.w3cplus.com/blog/tags/11.html?page=6", domain_name: "www.w3cplus.com")
Bookmark.create!(name: "CSS Reference - MDN", url: "https://developer.mozilla.org/en/CSS/CSS_Reference", domain_name: "developer.mozilla.org")
Bookmark.create!(name: "Ribbon | CSS-Tricks", url: "http://css-tricks.com/snippets/css/ribbon/", domain_name: "css-tricks.com")
Bookmark.create!(name: "Box Random Position", url: "http://demo.superdit.com/random_position_inside_container/", domain_name: "demo.superdit.com")
Bookmark.create!(name: "苗栗七朵花老師魔法團", url: "http://www.lazyfrog.tw/view.php?id=136", domain_name: "www.lazyfrog.tw")
Bookmark.create!(name: "Anatomy of a Laugh Track", url: "http://cnx.org/content/m15644/latest/?collection=col10503/latest", domain_name: "cnx.org")
Bookmark.create!(name: "www.cocoalab.com/BecomeAnXcoder%28TChinese%29.pdf", url: "http://www.cocoalab.com/BecomeAnXcoder%28TChinese%29.pdf", domain_name: "www.cocoalab.com")
Bookmark.create!(name: "audio annotation software - Google 搜尋", url: "https://www.google.com.tw/search?aq=0&oq=audio+annotation&sugexp=chrome,mod=11&sourceid=chrome&ie=UTF-8&q=audio+annotation+software", domain_name: "www.google.com.tw")
Bookmark.create!(name: "Amazon CloudFront FAQs", url: "http://aws.amazon.com/cloudfront/faqs/", domain_name: "aws.amazon.com")
Bookmark.create!(name: "html5 audio streaming s3 - Google 搜尋", url: "https://www.google.com.tw/search?sugexp=chrome,mod=11&sourceid=chrome&ie=UTF-8&q=html5+audio+streaming+s3", domain_name: "www.google.com.tw")
Bookmark.create!(name: "Create a Simple Music Streaming App with Ruby on Rails | Nettuts+", url: "http://net.tutsplus.com/tutorials/create-a-simple-music-streaming-app-with-ruby-on-rails/", domain_name: "net.tutsplus.com")
Bookmark.create!(name: "rails guide - Google 搜尋", url: "https://www.google.com.tw/search?sugexp=chrome,mod=11&sourceid=chrome&ie=UTF-8&q=rails+guide", domain_name: "www.google.com.tw")
Bookmark.create!(name: "Ruby on Rails Guides: Active Record Validations and Callbacks", url: "http://guides.rubyonrails.org/active_record_validations_callbacks.html", domain_name: "guides.rubyonrails.org")
Bookmark.create!(name: "The Ruby Toolbox - Devise: Flexible authentication solution for Rails with Warden", url: "https://www.ruby-toolbox.com/projects/devise", domain_name: "www.ruby-toolbox.com")
Bookmark.create!(name: "The Ruby Toolbox - Cancan: Simple authorization solution for Rails which is decoupled from user roles. All...", url: "https://www.ruby-toolbox.com/projects/cancan", domain_name: "www.ruby-toolbox.com")
Bookmark.create!(name: "jQuery UI - Slider Demos & Documentation", url: "http://jqueryui.com/demos/slider/#event-slide", domain_name: "jqueryui.com")
Bookmark.create!(name: "Ruby on Rails Tutorial: Learn Rails by Example book and screencasts by Michael Hartl", url: "http://ruby.railstutorial.org/purchases?payer_email=raphaeltnfsh%40gmail.com&txn_id=4AJ9019059403373K&first_name=%1A%1A&last_name=%1A&payment_status=Completed&currency=USD&custom=1087394&client_id=126476&gross=125.00&hash=911d6bdc2a49eee78f938673b2e6b63a", domain_name: "ruby.railstutorial.org")
Bookmark.create!(name: "Index of Classes & Methods in Ruby 1.9.3 (Ruby 1.9.3)", url: "http://ruby-doc.org/core-1.9.3/", domain_name: "ruby-doc.org")
Bookmark.create!(name: "Less · Twitter Bootstrap", url: "http://twitter.github.com/bootstrap/less.html#builtWith", domain_name: "twitter.github.com")
Bookmark.create!(name: "Rubular: a Ruby regular expression editor and tester", url: "http://rubular.com/", domain_name: "rubular.com")
Bookmark.create!(name: "Ruby on Rails Guides", url: "http://guides.rubyonrails.org/", domain_name: "guides.rubyonrails.org")
Bookmark.create!(name: "Román Cortés » Pure CSS Coke Can", url: "http://www.romancortes.com/blog/pure-css-coke-can/", domain_name: "www.romancortes.com")
Bookmark.create!(name: "Tiny Scrollbar: A lightweight jQuery plugin", url: "http://baijs.nl/tinyscrollbar/", domain_name: "baijs.nl")
Bookmark.create!(name: "Twitter Bootstrap", url: "http://twitter.github.com/bootstrap/", domain_name: "twitter.github.com")
Bookmark.create!(name: "(2) GUNNAR可試戴店家/診所資訊 (2012/6/27)", url: "https://www.facebook.com/note.php?note_id=143888505672428", domain_name: "www.facebook.com")
Bookmark.create!(name: "自訂搜尋引擎", url: "http://www.google.com/cse/", domain_name: "www.google.com")
Bookmark.create!(name: "哈佛大學最受歡迎的課程=》幸福課 @ 歡迎來到 建興 的部落格 :: 痞客邦 PIXNET ::", url: "http://dragonlion.pixnet.net/blog/post/31851145-%E5%93%88%E4%BD%9B%E5%A4%A7%E5%AD%B8%E6%9C%80%E5%8F%97%E6%AD%A1%E8%BF%8E%E7%9A%84%E8%AA%B2%E7%A8%8B%3D%E3%80%8B%E5%B9%B8%E7%A6%8F%E8%AA%B2", domain_name: "dragonlion.pixnet.net")
Bookmark.create!(name: "appWorks", url: "https://maps.google.com.tw/maps?hl=zh-TW&safe=off&ie=UTF-8&q=appWorks&fb=1&gl=tw&hq=appWorks&hnear=0x3442ac6b61dbbd9d:0xc0c243da98cba64b,%E5%8F%B0%E5%8C%97%E5%B8%82&cid=0,0,1815435503043542231&ei=5XQfUISrNcidmQXMoYHYCw&ved=0CK0BEPwSMAA", domain_name: "maps.google.com.tw")
Bookmark.create!(name: "阿正老師教你免費玩Amazon EC2雲端主機(下篇)：主機實戰篇 | ㊣軟體玩家", url: "http://blog.soft.idv.tw/?p=824&page=2", domain_name: "blog.soft.idv.tw")
Bookmark.create!(name: "創業公司招聘時需要詢問的 11 個問題 | TechOrange", url: "http://techorange.com/2012/06/26/11-hiring-questions-for-startups/", domain_name: "techorange.com")
Bookmark.create!(name: "LiveAll - 重現你們珍貴的回憶", url: "http://www.liveall.com/", domain_name: "www.liveall.com")
Bookmark.create!(name: "xdxd - Google 搜尋", url: "https://www.google.com/search?q=xdxd&aq=f&sugexp=chrome,mod=4&sourceid=chrome&ie=UTF-8", domain_name: "www.google.com")
Bookmark.create!(name: "Blueprint: A CSS Framework | Spend your time innovating, not replicating", url: "http://blueprintcss.org/", domain_name: "blueprintcss.org")
Bookmark.create!(name: "Mr.Travelo | 我的旅遊書", url: "http://mrtravelo.com/", domain_name: "mrtravelo.com")
Bookmark.create!(name: "Read EXIF data with Javascript - Nihilogic", url: "http://blog.nihilogic.dk/2008/05/reading-exif-data-with-javascript.html", domain_name: "blog.nihilogic.dk")
Bookmark.create!(name: "Wall Photos", url: "https://www.facebook.com/photo.php?fbid=459595630737608&set=a.401911376506034.92327.295830240447482&type=1&ref=nf", domain_name: "www.facebook.com")
Bookmark.create!(name: "筆耕歲月: 給電子電機人的建議", url: "http://wh012027.blogspot.com/2010/01/blog-post_31.html", domain_name: "wh012027.blogspot.com")
Bookmark.create!(name: "交資夢想 | 交大資工，交織夢想。", url: "http://nctucs.wordpress.com/", domain_name: "nctucs.wordpress.com")
Bookmark.create!(name: "留學：SOP解析 -- 2009/5/9更新 @ 倫倫的小blog :: 痞客邦 PIXNET ::", url: "http://xination.pixnet.net/blog/post/21739595", domain_name: "xination.pixnet.net")
Bookmark.create!(name: "靜謐。在灰藍天空下 - MIT，我的生活紀錄 [每個第一次]", url: "http://www.wretch.cc/blog/eggchi/11932028", domain_name: "www.wretch.cc")
Bookmark.create!(name: "1個月上美國名校！ - 文章分類: 一個月內讓你申請上美國名校！", url: "http://www.wretch.cc/blog/HenryLiu&category_id=8422659", domain_name: "www.wretch.cc")
Bookmark.create!(name: "CSS Reference - MDN", url: "https://developer.mozilla.org/en/CSS_Reference", domain_name: "developer.mozilla.org")
Bookmark.create!(name: "CSS-Tricks", url: "http://css-tricks.com/", domain_name: "css-tricks.com")
Bookmark.create!(name: "HTML5 Boilerplate - A rock-solid default template for HTML5 awesome.", url: "http://html5boilerplate.com/", domain_name: "html5boilerplate.com")
Bookmark.create!(name: "A Book Apart, Welcome", url: "http://www.abookapart.com/", domain_name: "www.abookapart.com")
Bookmark.create!(name: "#110: Quick Overview of CSS Position Values | CSS-Tricks", url: "http://css-tricks.com/video-screencasts/110-quick-overview-of-css-position-values/", domain_name: "css-tricks.com")
Bookmark.create!(name: "記事本形式", url: "http://www.4templates.com/website-templates/441656833-WT00828/demo/#brown", domain_name: "www.4templates.com")
Bookmark.create!(name: "木質", url: "http://www.4templates.com/website-templates/879223847-WT00873/demo/#green", domain_name: "www.4templates.com")
Bookmark.create!(name: "紙質", url: "http://www.4templates.com/website-templates/712196742-WT00889/demo/#brown", domain_name: "www.4templates.com")
Bookmark.create!(name: "Git Cheatsheet", url: "http://ndpsoftware.com/git-cheatsheet.html#loc=index;", domain_name: "ndpsoftware.com")
Bookmark.create!(name: "電工實驗(通信專題)", url: "https://ceiba.ntu.edu.tw/course/63fc8a/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "Speech Lab - courses", url: "http://speech.ee.ntu.edu.tw/courses/DSP2012Spring/", domain_name: "speech.ee.ntu.edu.tw")
Bookmark.create!(name: "通信原理", url: "http://santos.ee.ntu.edu.tw/", domain_name: "santos.ee.ntu.edu.tw")
Bookmark.create!(name: "演算法", url: "https://ceiba.ntu.edu.tw/course/cc3f8d/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "Signal and System", url: "http://speech.ee.ntu.edu.tw/courses/SS2012spring/", domain_name: "speech.ee.ntu.edu.tw")
Bookmark.create!(name: "無線行動網路導論", url: "https://ceiba.ntu.edu.tw/course/72831d/index.htm", domain_name: "ceiba.ntu.edu.tw")
Bookmark.create!(name: "Chart of distribution relationships", url: "http://www.johndcook.com/distribution_chart.html", domain_name: "www.johndcook.com")
Bookmark.create!(name: "wcnlab.niu.edu.tw/教學投影片/通訊原理/通訊原理_Chapter5.pdf", url: "http://wcnlab.niu.edu.tw/%E6%95%99%E5%AD%B8%E6%8A%95%E5%BD%B1%E7%89%87/%E9%80%9A%E8%A8%8A%E5%8E%9F%E7%90%86/%E9%80%9A%E8%A8%8A%E5%8E%9F%E7%90%86_Chapter5.pdf", domain_name: "wcnlab.niu.edu.tw")
Bookmark.create!(name: "NS2 使用說明手冊", url: "http://hpds.ee.ncku.edu.tw/~smallko/ns2/ns2.htm", domain_name: "hpds.ee.ncku.edu.tw")
Bookmark.create!(name: "Communication Systems 4Th Edition Simon Haykin With Solutions Manual.pdf_免费高速下载_新浪爱问共享资料", url: "http://ishare.iask.sina.com.cn/f/24137395.html", domain_name: "ishare.iask.sina.com.cn")
Bookmark.create!(name: "Solution Manual for Communication Systems Haykin 4th Edition[1]", url: "http://www.scribd.com/doc/29094031/Solution-Manual-for-Communication-Systems-Haykin-4th-Edition-1", domain_name: "www.scribd.com")
Bookmark.create!(name: "www.naun.org/journals/computers/ijcomputers-53.pdf", url: "http://www.naun.org/journals/computers/ijcomputers-53.pdf", domain_name: "www.naun.org")
Bookmark.create!(name: "停班停課查詢", url: "http://www.more.game.tw/cpa2.html", domain_name: "www.more.game.tw")
Bookmark.create!(name: "行政院人事行政總處全球資訊網-天然災害停止辦公及上課情形查詢", url: "http://www.cpa.gov.tw/", domain_name: "www.cpa.gov.tw")
Bookmark.create!(name: "Overview | CloudFlare | The web performance & security company", url: "http://www.cloudflare.com/overview", domain_name: "www.cloudflare.com")
Bookmark.create!(name: "Gin Admin - Live Preview - WrapBootstrap", url: "http://wrapbootstrap.com/preview/WB0L805L0", domain_name: "wrapbootstrap.com")
Bookmark.create!(name: "Unicorn - Admin Template - Live Preview - WrapBootstrap", url: "http://wrapbootstrap.com/preview/WB0F35928", domain_name: "wrapbootstrap.com")
Bookmark.create!(name: "Twitter", url: "https://twitter.com/", domain_name: "twitter.com")
Bookmark.create!(name: "VAN698影視吧|電影|戲劇|偶像劇|綜藝|日劇|韓劇|歐美劇|動漫|音樂MV|記錄片|體育|教育-首頁", url: "http://www.van698.com/movie/", domain_name: "www.van698.com")
Bookmark.create!(name: "CoffeeScript", url: "http://coffeescript.org/", domain_name: "coffeescript.org")
Bookmark.create!(name: "Announcements", url: "https://class.coursera.org/networks-2012-001/class/index", domain_name: "class.coursera.org")
Bookmark.create!(name: "Browse Palettes :: COLOURlovers", url: "http://www.colourlovers.com/palettes/most-loved/all-time/", domain_name: "www.colourlovers.com")
Bookmark.create!(name: "Google Web Fonts", url: "http://www.google.com/webfonts", domain_name: "www.google.com")
Bookmark.create!(name: "(1) 詹雨謙", url: "https://www.facebook.com/raphaeltnfsh", domain_name: "www.facebook.com")
Bookmark.create!(name: "dafont.com", url: "http://www.dafont.com/", domain_name: "www.dafont.com")
Bookmark.create!(name: "Fancy > Comic fonts | dafont.com", url: "http://www.dafont.com/theme.php?cat=102&page=2", domain_name: "www.dafont.com")
Bookmark.create!(name: "歡迎來到 Flickr - 相片分享", url: "http://www.flickr.com/", domain_name: "www.flickr.com")
Bookmark.create!(name: "Bookmark Icons - Download 78 Free Bookmark icons here - Page 2", url: "http://www.iconarchive.com/search?q=bookmark&page=2", domain_name: "www.iconarchive.com")
Bookmark.create!(name: "When can I use... Support tables for HTML5, CSS3, etc", url: "http://caniuse.com/", domain_name: "caniuse.com")
Bookmark.create!(name: "Diagram v2 Iconset (32 icons) | Double-J Design", url: "http://www.iconarchive.com/show/diagram-v2-icons-by-double-j-design.html", domain_name: "www.iconarchive.com")
Bookmark.create!(name: "Best CSS3 Button Maker: Button X", url: "http://www.webarti.com/best-CSS3-button-maker/", domain_name: "www.webarti.com")
Bookmark.create!(name: "bookmarklet - Google 搜尋", url: "https://www.google.com/search?aq=f&oq=bookmarklet&sugexp=chrome,mod=13&sourceid=chrome&client=ubuntu&channel=cs&ie=UTF-8&q=bookmarklet", domain_name: "www.google.com")
Bookmark.create!(name: "railstutorial gemfils - Google 搜尋", url: "https://www.google.com/search?hl=zh-TW&client=ubuntu&hs=kdL&channel=cs&q=railstutorial+gemfils&oq=railstutorial+gemfils&gs_l=serp.3..0i19.3193.3193.0.3388.1.1.0.0.0.0.71.71.1.1.0...0.0...1c.PljL67wOG6k", domain_name: "www.google.com")
Bookmark.create!(name: "#323 Backbone on Rails Part 1 (pro) - RailsCasts", url: "http://railscasts.com/episodes/323-backbone-on-rails-part-1?view=asciicast", domain_name: "railscasts.com")
Bookmark.create!(name: "ipath", url: "http://ipath.tw/", domain_name: "ipath.tw")
Bookmark.create!(name: "Js2coffee: convert JavaScript code to CoffeeScript", url: "http://js2coffee.org/", domain_name: "js2coffee.org")
